import Head from "next/head";
import { useContext, useEffect, useState } from "react";
import Navbar from "./components/Navbar";
import { TokenContext } from "./lib/TokenContext";

export default function Home() {
	const { tokenData } = useContext(TokenContext);

	useEffect(() => {
		console.log(tokenData);
	}, [tokenData]);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="flex flex-row gap-6 container h-screen font-poppins">
					<div className="flex">
						<Navbar />
					</div>
					<div className="bg-white flex flex-1">
						<div className="mx-auto max-w-2xl py-12 px-4 sm:px-6 lg:px-0">
							<h1 className="text-center text-3xl font-semibold tracking-tight text-gray-900 sm:text-4xl">
								Currently Owned NFTs
							</h1>

							<div className="mt-12">
								<section aria-labelledby="cart-heading">
									<h2 id="cart-heading" className="sr-only">
										NFTs owned
									</h2>

									<ul
										role="list"
										className="divide-y divide-gray-200 border-t border-b border-gray-200"
									>
										{tokenData &&
											tokenData.map((nft: any) => (
												<li className="flex py-6">
													<div className="flex-shrink-0">
														<img
															src={nft.current_token_data.metadata_uri}
															className="h-24 w-24 rounded-md object-cover object-center sm:h-32 sm:w-32"
														/>
													</div>

													<div className="ml-4 flex flex-1 flex-col sm:ml-6">
														<div>
															<div className="flex justify-between">
																<h4 className="text-sm font-medium text-gray-700 hover:text-gray-800">
																	{nft.current_token_data.name}
																</h4>
															</div>
															<p className="mt-1 text-sm text-gray-500">
																Serial No: {nft.collection_name}
															</p>
														</div>

														<div className="mt-4 flex flex-1 items-end justify-between">
															<a href={nft.collection_name}>
																<button
																	type="button"
																	className="text-sm font-medium text-mainBlue hover:text-darkBlue"
																>
																	<span>Send</span>
																</button>
															</a>
														</div>
													</div>
												</li>
											))}
									</ul>
								</section>
							</div>
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
