import Head from "next/head";
import { useWallet } from "@aptos-labs/wallet-adapter-react";
import { WalletSelector } from "@aptos-labs/wallet-adapter-ant-design";
import { createToken, sendToken } from "./components/utils";
import { useEffect, useState } from "react";
import { useAuth } from "./lib/AuthContext";
import { useRouter } from "next/router";
import Navbar from "./components/Navbar";

export default function Home() {
	function handleCreateToken(e) {
		// Prevent the browser from reloading the page
		e.preventDefault();

		// Read the form data
		const form = e.target;
		const formData = new FormData(form);
		const formJson = Object.fromEntries(formData.entries());
		console.log(formJson);
		createToken(
			formJson.address,
			formJson.name,
			formJson.serialNum,
			formJson.desc,
			formJson.img
		);
	}

	function handleSendToken(e) {
		// Prevent the browser from reloading the page
		e.preventDefault();

		// Read the form data
		const form = e.target;
		const formData = new FormData(form);
		const formJson = Object.fromEntries(formData.entries());
		console.log(formJson);
		sendToken(
			formJson.address,
			formJson.name,
			formJson.serialNum,
			formJson.dest
		);
	}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="flex flex-row gap-6 container h-screen">
					<div className="flex">
						<Navbar />
					</div>
					<div>
						<WalletSelector />
						<h1>Create Token</h1>
						<form method="post" onSubmit={handleCreateToken}>
							<label>
								Address: <input name="address" />
							</label>
							<label>
								Name: <input name="name" />
							</label>
							<label>
								SerialNum: <input name="serialNum" />
							</label>
							<label>
								Desc: <input name="desc" />
							</label>
							<label>
								Img: <input name="img" />
							</label>
							<button type="submit">Submit form</button>
						</form>
						<h1>Send Token</h1>
						<form method="post" onSubmit={handleSendToken}>
							<label>
								Address: <input name="address" />
							</label>
							<label>
								Name: <input name="name" />
							</label>
							<label>
								SerialNum: <input name="serialNum" />
							</label>
							<label>
								Dest: <input name="dest" />
							</label>
							<button type="submit">Submit form</button>
						</form>
					</div>
				</div>
			</main>
		</>
	);
}
